INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(1,'Kedokteran','Reguler','Kedokteran','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(2,'Matematika','Reguler','Matematika dan Pengetahuan Alam','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(3,'Teknik Sipil','Reguler','Teknik','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(4,'Ilmu Komputer','Reguler','Ilmu Komputer','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(5,'Kedokteran','Reguler','Kedokteran','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(6,'Fisika','Reguler','Matematika dan Pengetahuan Alam','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(7,'Teknik Sipil','Reguler','Teknik','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(8,'Ilmu Komputer','Reguler','Ilmu Komputer','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(9,'Kedokteran','Reguler','Kedokteran','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(10,'Biologi','Reguler','Matematika dan Pengetahuan Alam','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(11,'Teknik Sipil','Reguler','Teknik','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(12,'Ilmu Komputer','Reguler','Ilmu Komputer','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(13,'Kedokteran','Internasional','Kedokteran','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(14,'Biologi','Internasional','Matematika dan Pengetahuan Alam','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(15,'Teknik Industri','Internasional','Teknik','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(16,'Ilmu Komputer','Internasional','Ilmu Komputer','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(17,'Kedokteran','Paralel','Kedokteran','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(18,'Biologi','Paralel','Matematika dan Pengetahuan Alam','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(19,'Teknik Industri','Paralel','Teknik','S1');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(20,'Ilmu Komputer','Paralel','Ilmu Komputer','S1');

INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(21,'Kedokteran','Reguler','Kedokteran','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(22,'Matematika','Reguler','Matematika dan Pengetahuan Alam','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(23,'Teknik Sipil','Reguler','Teknik','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(24,'Ilmu Komputer','Reguler','Ilmu Komputer','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(25,'Kedokteran','Reguler','Kedokteran','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(26,'Fisika','Reguler','Matematika dan Pengetahuan Alam','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(27,'Teknik Sipil','Reguler','Teknik','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(28,'Ilmu Komputer','Reguler','Ilmu Komputer','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(29,'Kedokteran','Reguler','Kedokteran','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(30,'Biologi','Reguler','Matematika dan Pengetahuan Alam','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(31,'Teknik Sipil','Reguler','Teknik','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(32,'Ilmu Komputer','Reguler','Ilmu Komputer','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(33,'Kedokteran','Internasional','Kedokteran','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(34,'Biologi','Internasional','Matematika dan Pengetahuan Alam','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(35,'Teknik Industri','Internasional','Teknik','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(36,'Ilmu Komputer','Internasional','Ilmu Komputer','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(37,'Kedokteran','Paralel','Kedokteran','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(38,'Biologi','Paralel','Matematika dan Pengetahuan Alam','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(39,'Teknik Industri','Paralel','Teknik','S2');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(40,'Ilmu Komputer','Paralel','Ilmu Komputer','S2');

INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(41,'Kedokteran','Reguler','Kedokteran','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(42,'Matematika','Reguler','Matematika dan Pengetahuan Alam','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(43,'Teknik Sipil','Reguler','Teknik','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(44,'Ilmu Komputer','Reguler','Ilmu Komputer','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(45,'Kedokteran','Reguler','Kedokteran','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(46,'Fisika','Reguler','Matematika dan Pengetahuan Alam','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(47,'Teknik Sipil','Reguler','Teknik','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(48,'Ilmu Komputer','Reguler','Ilmu Komputer','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(49,'Kedokteran','Reguler','Kedokteran','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(50,'Biologi','Reguler','Matematika dan Pengetahuan Alam','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(51,'Teknik Sipil','Reguler','Teknik','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(52,'Ilmu Komputer','Reguler','Ilmu Komputer','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(53,'Kedokteran','Internasional','Kedokteran','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(54,'Biologi','Internasional','Matematika dan Pengetahuan Alam','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(55,'Teknik Industri','Internasional','Teknik','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(56,'Ilmu Komputer','Internasional','Ilmu Komputer','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(57,'Kedokteran','Paralel','Kedokteran','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(58,'Biologi','Paralel','Matematika dan Pengetahuan Alam','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(59,'Teknik Industri','Paralel','Teknik','S3');
INSERT INTO PROGRAM_STUDI(kode,nama,jenis_kelas,nama_fakultas,jenjang) VALUES(60,'Ilmu Komputer','Paralel','Ilmu Komputer','S3');
